# Generated by Django 4.1.13 on 2024-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=15)),
                ('discount', models.IntegerField()),
                ('duration', models.DurationField()),
                ('author_name', models.CharField(max_length=40)),
            ],
        ),
    ]
